//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTap6_61134311.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien
    {
        [Display(Name = "Mã nhân viên")]
        public string MaNV { get; set; }
        [Display(Name = "Họ nhân viên")]
        public string HoNV { get; set; }
        [Display(Name = "Tên nhân viên")]
        public string TenNV { get; set; }
        [Display(Name = "Giới tính")]
        public Nullable<bool> GioiTinh { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Ngày sinh")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [DisplayFormat(DataFormatString = "{0:#,##0}", ApplyFormatInEditMode = true)]
        [Display(Name = "Lương")]
        public Nullable<int> Luong { get; set; }
        [Display(Name = "Ảnh nhân viên")]
        public string AnhNV { get; set; }
        [Display(Name = "Địa chỉ")]
        public string DiaChi { get; set; }
        [Display(Name = "Mã phòng ban")]
        public string MaPB { get; set; }
        [Display(Name = "Phòng ban")]
        public virtual PhongBan PhongBan { get; set; }
    }
}
